import { Navbar, Footer } from "@/components";
import { helveticaNeue, sebNeue } from "@/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sebNeue.variable} ${helveticaNeue.variable}`}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

